title: Shouting to the void
author: Sam Reiswig
email: sam.reiswig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Topics I find interesting in ML, Math, Computer Science and Software Engineering.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: chirpy
